# Generated by Django 2.2.3 on 2019-07-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='created_by',
            new_name='posted_by',
        ),
    ]
